name:
  first_name: zakaria
  secret: my-password
  pass: 9Kf7Bq2mXxYw8PzLrT6NcVjA4HsEeQ
  token: ghp_AbC123xYz456D7Ef89GhI01JkLmNoPqRsTuV
  mot_de_passe: 1234
  password: Sonne98Gelb_wALD9
  passwort: Sonne98Gelb_wALD9
  new_password: Sonne98Gelb_wALD9u8
